name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install latest stable toolchain with clippy and rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: actions/checkout@v6
      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          name: clippy
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
      - name: Rustfmt check
        run: cargo fmt -- --check
