name: Release

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Install latest stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v6
      - name: Build release
        run: cargo build --release
      - name: Create zip archive
        run: zip -j ampsim-launcher.zip target/release/*.exe
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ampsim-launcher.zip
